from django.db import models
import uuid

# DELETE FROM django_migrations WHERE app='pilotlog';

class PilotLog(models.Model):
    guid = models.CharField(max_length=36, unique=True)
    table = models.CharField(max_length=255, blank=True, null=True) 
    fin = models.CharField(max_length=255, blank=True, null=True)
    sea = models.BooleanField(default=False)
    tmg = models.BooleanField(default=False)
    efis = models.BooleanField(default=False)
    fnpt = models.IntegerField(default=0)
    make = models.CharField(max_length=255, blank=True, null=True)
    run2 = models.BooleanField(default=False)
    class_category = models.IntegerField(default=0)
    model = models.CharField(max_length=255, blank=True, null=True)
    power = models.IntegerField(default=0)
    seats = models.IntegerField(default=0)
    active = models.BooleanField(default=False)
    kg5700 = models.BooleanField(default=False)
    rating = models.CharField(max_length=255, blank=True, null=True)
    company = models.CharField(max_length=255, blank=True, null=True)
    complex = models.BooleanField(default=False)
    cond_log = models.IntegerField(default=0)
    fav_list = models.BooleanField(default=False)
    category = models.IntegerField(default=0)
    high_perf = models.BooleanField(default=False)
    sub_model = models.CharField(max_length=255, blank=True, null=True)
    aerobatic = models.BooleanField(default=False)
    ref_search = models.CharField(max_length=255, blank=True, null=True)
    reference = models.CharField(max_length=255, blank=True, null=True)
    tailwheel = models.BooleanField(default=False)
    default_app = models.IntegerField(default=0)
    default_log = models.IntegerField(default=0)
    default_ops = models.IntegerField(default=0)
    device_code = models.IntegerField(default=0)
    aircraft_code = models.CharField(max_length=255, blank=True, null=True)
    default_launch = models.IntegerField(default=0)
    record_modified = models.DateTimeField(blank=True, null=True)
    platform = models.IntegerField(default=0)
    modified = models.BigIntegerField(default=0)
