# Generated by Django 5.0.7 on 2024-08-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PilotLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=36, unique=True)),
                ('table', models.CharField(blank=True, max_length=255, null=True)),
                ('fin', models.CharField(blank=True, max_length=255, null=True)),
                ('sea', models.BooleanField(default=False)),
                ('tmg', models.BooleanField(default=False)),
                ('efis', models.BooleanField(default=False)),
                ('fnpt', models.IntegerField(default=0)),
                ('make', models.CharField(blank=True, max_length=255, null=True)),
                ('run2', models.BooleanField(default=False)),
                ('class_category', models.IntegerField(default=0)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('power', models.IntegerField(default=0)),
                ('seats', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
                ('kg5700', models.BooleanField(default=False)),
                ('rating', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('complex', models.BooleanField(default=False)),
                ('cond_log', models.IntegerField(default=0)),
                ('fav_list', models.BooleanField(default=False)),
                ('category', models.IntegerField(default=0)),
                ('high_perf', models.BooleanField(default=False)),
                ('sub_model', models.CharField(blank=True, max_length=255, null=True)),
                ('aerobatic', models.BooleanField(default=False)),
                ('ref_search', models.CharField(blank=True, max_length=255, null=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('tailwheel', models.BooleanField(default=False)),
                ('default_app', models.IntegerField(default=0)),
                ('default_log', models.IntegerField(default=0)),
                ('default_ops', models.IntegerField(default=0)),
                ('device_code', models.IntegerField(default=0)),
                ('aircraft_code', models.CharField(blank=True, max_length=255, null=True)),
                ('default_launch', models.IntegerField(default=0)),
                ('record_modified', models.DateTimeField(blank=True, null=True)),
                ('platform', models.IntegerField(default=0)),
                ('modified', models.BigIntegerField(default=0)),
            ],
        ),
    ]
